### ISSUE TITLE
env.epidemic

### ISSUE THREAD

**Issue by alittt5** [xxfwin/NAGASIL#1]
I can't find the Python package env.epidemic。

**Comment by xxfwin** [comment]
Hi alittt5,

  Sorry for the late reply, I'm on leave now, but thanks for raising this question. It looks like the env folder has been ignored, I will upload them shortly.

**Comment by xxfwin** [comment]
Added missing files, the problem should be fixed now, if this problem persists please re-open this issue.

Cheers

**Comment by alittt5** [comment]
Thank you.^.^
